name: animateSwarm
channels:
  - conda-forge
dependencies:
  - python>=3.7 
  - jupyter
  - notebook
  - pip>=19
  - scipy>=0.18.1
  - matplotlib>=1.5.1
  - pathlib>=1.0
  - h5py>=2.6.0
  - pip:
     - -e .
